project:
  type: website
  output-dir: docs

website:
  title: "Trishna Saikia"
  site-url: "https://trishnasaikia.github.io"
  description: "PhD Researcher in Machine Learning, Computer Vision, and Physiological Computing at IIT Indore."
  favicon: assets/silvia/img/logo_rounded.svg
  page-navigation: true
  back-to-top-navigation: true

  navbar:
    logo: assets/silvia/img/logo_rounded.svg
    tools:
      - icon: github
        href: https://github.com/TrishnaSaikia
    right:
      - text: Research
        aria-label: "Research"
        href: research/index.qmd

      - text: Teaching
        aria-label: "Teaching"
        href: teaching/index.qmd

      - text: Projects
        aria-label: "Projects"
        href: project/index.qmd

      - text: Miscellaneous
        aria-label: "Miscellaneous"
        href: miscellaneous/index.qmd

      - text: CV
        aria-label: "Curriculum Vitae"
        href: assets/CV_Trishna_Saikia.pdf

  page-footer:
    left: >-
      &#169; 2026 Trishna Saikia &#8729; Made with [Quarto](https://quarto.org)

    center: |
      <a class="link-dark me-1" href="https://www.linkedin.com/in/trishnasaikia/" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
      <a class="link-dark me-1" href="https://github.com/TrishnaSaikia" title="GitHub" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark me-1" href="https://scholar.google.com/citations?hl=en&user=G6G8ir0AAAAJ" title="Google Scholar" target="_blank" rel="noopener">{{< ai google-scholar >}}</a>
      <a class="link-dark me-1" href="https://orcid.org/0000-0002-3052-1689" title="ORCID" target="_blank" rel="noopener">{{< ai orcid >}}</a>
      <a class="link-dark me-1" href="mailto:trishnasaikia2521@gmail.com" title="Email" target="_blank" rel="noopener">{{< fa envelope >}}</a>

    right:
      - text: "Contact"
        aria-label: "Contact"
        href: contact.qmd

format:
  html:
    theme:
      light:
        - cosmo
        - assets/silvia-theme-light.scss
        - assets/silvia/colors-light.scss
        - assets/silvia/fonts.scss
      dark:
        - cosmo
        - assets/silvia-theme-dark.scss
        - assets/silvia/colors-dark.scss
    highlight-style:
      light: assets/silvia/a11y-light.theme
      dark: assets/silvia/a11y-dark.theme
    code-link: true
    pagetitle: "{{< meta title >}}"
    lightbox: true

execute:
  freeze: auto